
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/NewsList
    username: postgres
    password: Faolseans-8246
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

servlet:
  multipart:
    max-file-size: 200MB
    max-request-size: 200MB

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true