
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/NewsList
    username: postgres
    password: Faolseans-8246
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop